name: Daily Schaufele Alert
on:
  schedule:
    # This runs at 07:30 UTC (08:30 German time) every Mon-Fri
    - cron: '30 7 * * 1-5'
  workflow_dispatch: # This adds a button to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          MENSA_PASSWORD: ${{ secrets.MENSA_PASSWORD }}
        run: python schaeufele.py
